version: '3.9'
services:
  mongo:
    image: mongo
    container_name: mongoDb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: Students # or "admin"
    ports:
      - 27017:27017
    networks:
      - keploy-network

networks:
  keploy-network:
    external: true
